// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchEngine.Infrastructure.Persistence;

#nullable disable

namespace SearchEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchEngine.Domain.Base.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FinalScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ProviderItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ProviderItemId")
                        .IsUnique();

                    b.ToTable("ContentItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SearchEngine.Domain.Entities.TextContent", b =>
                {
                    b.HasBaseType("SearchEngine.Domain.Base.ContentItem");

                    b.Property<int>("Reactions")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingTimeMinutes")
                        .HasColumnType("integer");

                    b.ToTable("TextContents", (string)null);
                });

            modelBuilder.Entity("SearchEngine.Domain.Entities.VideoContent", b =>
                {
                    b.HasBaseType("SearchEngine.Domain.Base.ContentItem");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.ToTable("VideoContents", (string)null);
                });

            modelBuilder.Entity("SearchEngine.Domain.Entities.TextContent", b =>
                {
                    b.HasOne("SearchEngine.Domain.Base.ContentItem", null)
                        .WithOne()
                        .HasForeignKey("SearchEngine.Domain.Entities.TextContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SearchEngine.Domain.Entities.VideoContent", b =>
                {
                    b.HasOne("SearchEngine.Domain.Base.ContentItem", null)
                        .WithOne()
                        .HasForeignKey("SearchEngine.Domain.Entities.VideoContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
